### ISSUE TITLE
installation instructions appear to be incorrect

### ISSUE THREAD

**Issue by amtoine** [dead10ck/nu_plugin_dns#1]
it appears the [installation instructions](https://github.com/dead10ck/nu_plugin_dns#install) from README do not work :open_mouth:
```nushell
> register $"($env.CARGO_HOME)/bin/nu_plugin_dns"
Error: nu::parser::not_a_constant

  × Not a constant.
   ╭─[entry #12:1:1]
 1 │ register $"($env.CARGO_HOME)/bin/nu_plugin_dns"
   ·          ───────────────────┬──────────────────
   ·                             ╰── Value is not a parse-time constant
   ╰────
  help: Only a subset of expressions are allowed constants during parsing. Try using the 'const' command or typing the
        value literally.
```

## possible fix
change the install commands to
```nushell
nu --commands $"register ($env.CARGO_HOME)/bin/nu_plugin_dns"
```

**Comment by dead10ck** [comment]
Oops, that's what I get for not testing. Thanks, I'll use your suggestion

**Comment by amtoine** [comment]
> Oops, that's what I get for not testing.
>
ehe :wink: 

> Thanks, I'll use your suggestion
>
happy to help, this one is not the prettiest but it works until we allow `register` to take constants :smirk:
