### ISSUE TITLE
Nushell 0.84.1

### ISSUE THREAD

**Issue by fdncred** [dead10ck/nu_plugin_dns#2]
FYI - The latest dev version of nushell seriously breaks your code. I started making changes to it but ran out of time. I can put up an incomplete PR if you want to see what I started to change. It's mostly in your serde.rs file.

**Comment by dead10ck** [comment]
Yeah I noticed that the whole Value API was being reworked to be able to be valueless. Which is awesome because that will let me clean up all the useless `Span:: unknown()`s. But yeah I imagine it pretty much breaks everything in `serde.rs`.

**Comment by fdncred** [comment]
There will be Values with spans and UnspannedValues, but those changes aren't in yet. This PR is the one that is breaking everything at the mooment. https://github.com/nushell/nushell/pull/10103

**Comment by ZerdoX-x** [comment]
for me works with latest plugin and latest nu :)

**Comment by dead10ck** [comment]
Oh, I fixed this a little while ago, I just forgot to close this. 🙂
