### ISSUE TITLE
Issues installing nu_plugin_dns - homebrew user

### ISSUE THREAD

**Issue by maibarra** [dead10ck/nu_plugin_dns#6]
The following message appears when attempting to install `nu_plugin_dns`

```bash
cargo install nu_plugin_dns
nu --commands $"register ($env.CARGO_HOME)/bin/nu_plugin_dns"

Error: nu::parser::variable_not_found

  × Variable not found.
   ╭─[source:1:1]
 1 │ $register (.CARGO_HOME)/bin/nu_plugin_dns
   · ────┬────
   ·     ╰── variable not found.
   ╰────
```

Dependencies installed:
- `rust` , `cargo` : (installed through [homebrew](https://brew.sh))
- `nushell` (installed through [homebrew](https://brew.sh))

is there something I'm missing from the install steps?

**Comment by dead10ck** [comment]
I can't reproduce this. What version of nushell are you running?

**Comment by dead10ck** [comment]
Going to close this as I can't reproduce and haven't heard back. Let me know if you can provide more detail.
