### ISSUE TITLE
Error getting signaturesPlugin failed to load

### ISSUE THREAD

**Issue by mcshept** [dead10ck/nu_plugin_dns#8]
When trying to register the plugin I get the following error:
Plugin `Error: dns` read error:   × Error getting signaturesPlugin failed to load:
Plugin is compiled for nushell version 0.91.0, which is not compatible with version 0.92.2
╭─[entry #1:1:1]
 1 │ register ..\.cargo\bin\nu_plugin_dns.exe
   · ────┬───
   ·     ╰── Plugin failed to load: Plugin `dns` is compiled for nushell version 0.91.0, which is not compatible with version 0.92.2
   ╰────

**Comment by dead10ck** [comment]
Yes, 0.92 had some major breaking changes, so it took me some time to get things fixed. It is fixed in the latest master branch, but there are a couple other things I want to do before making a new release. But for the time being, you can pull the repo locally to get a working version.

**Comment by dead10ck** [comment]
This has been fixed in 3.0.0
